repos:
  - repo: local
    hooks:
      - id: code-check
        name: code-check (local)
        entry: uv run make check
        language: system
        pass_filenames: false
        always_run: true
